"""add password field to users

Revision ID: cb0b0b66ca95
Revises: 0e9d70c3cd26
Create Date: 2025-08-06 22:20:47.183317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cb0b0b66ca95'
down_revision: Union[str, Sequence[str], None] = '0e9d70c3cd26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('blogs', sa.Column('markdown_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('blogs', sa.Column('compiled_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('blogs', 'content')
    op.add_column('users', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('blogs', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'compiled_content')
    op.drop_column('blogs', 'markdown_content')
    op.drop_column('blogs', 'summary')
    # ### end Alembic commands ###
